package com.lijin.mylab.dao.mybatis.model;

public class StockInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stock_info.stock_no
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    private String stockNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stock_info.stock_nm
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    private String stockNm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stock_info.stock_no
     *
     * @return the value of tbl_stock_info.stock_no
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    public String getStockNo() {
        return stockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stock_info.stock_no
     *
     * @param stockNo the value for tbl_stock_info.stock_no
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    public void setStockNo(String stockNo) {
        this.stockNo = stockNo == null ? null : stockNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stock_info.stock_nm
     *
     * @return the value of tbl_stock_info.stock_nm
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    public String getStockNm() {
        return stockNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stock_info.stock_nm
     *
     * @param stockNm the value for tbl_stock_info.stock_nm
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    public void setStockNm(String stockNm) {
        this.stockNm = stockNm == null ? null : stockNm.trim();
    }
}