package com.lijin.mylab.dao.mybatis.model;

public class StockPositionLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stock_position_log.log_id
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    private Integer logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stock_position_log.stock_no
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    private String stockNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stock_position_log.trans_number
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    private Integer transNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stock_position_log.buy_in_dt
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    private String buyInDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stock_position_log.buy_in_at
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    private Integer buyInAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stock_position_log.sell_out_dt
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    private String sellOutDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stock_position_log.sell_out_at
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    private Integer sellOutAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stock_position_log.status
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stock_position_log.log_id
     *
     * @return the value of tbl_stock_position_log.log_id
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stock_position_log.log_id
     *
     * @param logId the value for tbl_stock_position_log.log_id
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stock_position_log.stock_no
     *
     * @return the value of tbl_stock_position_log.stock_no
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    public String getStockNo() {
        return stockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stock_position_log.stock_no
     *
     * @param stockNo the value for tbl_stock_position_log.stock_no
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    public void setStockNo(String stockNo) {
        this.stockNo = stockNo == null ? null : stockNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stock_position_log.trans_number
     *
     * @return the value of tbl_stock_position_log.trans_number
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    public Integer getTransNumber() {
        return transNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stock_position_log.trans_number
     *
     * @param transNumber the value for tbl_stock_position_log.trans_number
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    public void setTransNumber(Integer transNumber) {
        this.transNumber = transNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stock_position_log.buy_in_dt
     *
     * @return the value of tbl_stock_position_log.buy_in_dt
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    public String getBuyInDt() {
        return buyInDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stock_position_log.buy_in_dt
     *
     * @param buyInDt the value for tbl_stock_position_log.buy_in_dt
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    public void setBuyInDt(String buyInDt) {
        this.buyInDt = buyInDt == null ? null : buyInDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stock_position_log.buy_in_at
     *
     * @return the value of tbl_stock_position_log.buy_in_at
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    public Integer getBuyInAt() {
        return buyInAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stock_position_log.buy_in_at
     *
     * @param buyInAt the value for tbl_stock_position_log.buy_in_at
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    public void setBuyInAt(Integer buyInAt) {
        this.buyInAt = buyInAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stock_position_log.sell_out_dt
     *
     * @return the value of tbl_stock_position_log.sell_out_dt
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    public String getSellOutDt() {
        return sellOutDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stock_position_log.sell_out_dt
     *
     * @param sellOutDt the value for tbl_stock_position_log.sell_out_dt
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    public void setSellOutDt(String sellOutDt) {
        this.sellOutDt = sellOutDt == null ? null : sellOutDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stock_position_log.sell_out_at
     *
     * @return the value of tbl_stock_position_log.sell_out_at
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    public Integer getSellOutAt() {
        return sellOutAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stock_position_log.sell_out_at
     *
     * @param sellOutAt the value for tbl_stock_position_log.sell_out_at
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    public void setSellOutAt(Integer sellOutAt) {
        this.sellOutAt = sellOutAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stock_position_log.status
     *
     * @return the value of tbl_stock_position_log.status
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stock_position_log.status
     *
     * @param status the value for tbl_stock_position_log.status
     *
     * @mbg.generated Tue Nov 10 18:17:03 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}