package com.lijin.mylab.dao.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class StockPositionLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    protected List<Criteria> oredCriteria;

    private int startNum;

    private int pageSize;

    private boolean isPagination = false;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    public StockPositionLogExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public int getStartNum() {
        return startNum;
    }

    public int getPageSize() {
        return pageSize;
    }

    public boolean isPagination() {
        return isPagination;
    }

    public void setStartNum(int startNum) {
        this.isPagination = true;
        this.startNum = startNum;
    }

    public void setPageSize(int pageSize) {
        this.isPagination = true;
        this.pageSize = pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLogIdIsNull() {
            addCriterion("log_id is null");
            return (Criteria) this;
        }

        public Criteria andLogIdIsNotNull() {
            addCriterion("log_id is not null");
            return (Criteria) this;
        }

        public Criteria andLogIdEqualTo(Integer value) {
            addCriterion("log_id =", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotEqualTo(Integer value) {
            addCriterion("log_id <>", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdGreaterThan(Integer value) {
            addCriterion("log_id >", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("log_id >=", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdLessThan(Integer value) {
            addCriterion("log_id <", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdLessThanOrEqualTo(Integer value) {
            addCriterion("log_id <=", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdIn(List<Integer> values) {
            addCriterion("log_id in", values, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotIn(List<Integer> values) {
            addCriterion("log_id not in", values, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdBetween(Integer value1, Integer value2) {
            addCriterion("log_id between", value1, value2, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotBetween(Integer value1, Integer value2) {
            addCriterion("log_id not between", value1, value2, "logId");
            return (Criteria) this;
        }

        public Criteria andStockNoIsNull() {
            addCriterion("stock_no is null");
            return (Criteria) this;
        }

        public Criteria andStockNoIsNotNull() {
            addCriterion("stock_no is not null");
            return (Criteria) this;
        }

        public Criteria andStockNoEqualTo(String value) {
            addCriterion("stock_no =", value, "stockNo");
            return (Criteria) this;
        }

        public Criteria andStockNoNotEqualTo(String value) {
            addCriterion("stock_no <>", value, "stockNo");
            return (Criteria) this;
        }

        public Criteria andStockNoGreaterThan(String value) {
            addCriterion("stock_no >", value, "stockNo");
            return (Criteria) this;
        }

        public Criteria andStockNoGreaterThanOrEqualTo(String value) {
            addCriterion("stock_no >=", value, "stockNo");
            return (Criteria) this;
        }

        public Criteria andStockNoLessThan(String value) {
            addCriterion("stock_no <", value, "stockNo");
            return (Criteria) this;
        }

        public Criteria andStockNoLessThanOrEqualTo(String value) {
            addCriterion("stock_no <=", value, "stockNo");
            return (Criteria) this;
        }

        public Criteria andStockNoLike(String value) {
            addCriterion("stock_no like", value, "stockNo");
            return (Criteria) this;
        }

        public Criteria andStockNoNotLike(String value) {
            addCriterion("stock_no not like", value, "stockNo");
            return (Criteria) this;
        }

        public Criteria andStockNoIn(List<String> values) {
            addCriterion("stock_no in", values, "stockNo");
            return (Criteria) this;
        }

        public Criteria andStockNoNotIn(List<String> values) {
            addCriterion("stock_no not in", values, "stockNo");
            return (Criteria) this;
        }

        public Criteria andStockNoBetween(String value1, String value2) {
            addCriterion("stock_no between", value1, value2, "stockNo");
            return (Criteria) this;
        }

        public Criteria andStockNoNotBetween(String value1, String value2) {
            addCriterion("stock_no not between", value1, value2, "stockNo");
            return (Criteria) this;
        }

        public Criteria andTransNumberIsNull() {
            addCriterion("trans_number is null");
            return (Criteria) this;
        }

        public Criteria andTransNumberIsNotNull() {
            addCriterion("trans_number is not null");
            return (Criteria) this;
        }

        public Criteria andTransNumberEqualTo(Integer value) {
            addCriterion("trans_number =", value, "transNumber");
            return (Criteria) this;
        }

        public Criteria andTransNumberNotEqualTo(Integer value) {
            addCriterion("trans_number <>", value, "transNumber");
            return (Criteria) this;
        }

        public Criteria andTransNumberGreaterThan(Integer value) {
            addCriterion("trans_number >", value, "transNumber");
            return (Criteria) this;
        }

        public Criteria andTransNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("trans_number >=", value, "transNumber");
            return (Criteria) this;
        }

        public Criteria andTransNumberLessThan(Integer value) {
            addCriterion("trans_number <", value, "transNumber");
            return (Criteria) this;
        }

        public Criteria andTransNumberLessThanOrEqualTo(Integer value) {
            addCriterion("trans_number <=", value, "transNumber");
            return (Criteria) this;
        }

        public Criteria andTransNumberIn(List<Integer> values) {
            addCriterion("trans_number in", values, "transNumber");
            return (Criteria) this;
        }

        public Criteria andTransNumberNotIn(List<Integer> values) {
            addCriterion("trans_number not in", values, "transNumber");
            return (Criteria) this;
        }

        public Criteria andTransNumberBetween(Integer value1, Integer value2) {
            addCriterion("trans_number between", value1, value2, "transNumber");
            return (Criteria) this;
        }

        public Criteria andTransNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("trans_number not between", value1, value2, "transNumber");
            return (Criteria) this;
        }

        public Criteria andBuyInDtIsNull() {
            addCriterion("buy_in_dt is null");
            return (Criteria) this;
        }

        public Criteria andBuyInDtIsNotNull() {
            addCriterion("buy_in_dt is not null");
            return (Criteria) this;
        }

        public Criteria andBuyInDtEqualTo(String value) {
            addCriterion("buy_in_dt =", value, "buyInDt");
            return (Criteria) this;
        }

        public Criteria andBuyInDtNotEqualTo(String value) {
            addCriterion("buy_in_dt <>", value, "buyInDt");
            return (Criteria) this;
        }

        public Criteria andBuyInDtGreaterThan(String value) {
            addCriterion("buy_in_dt >", value, "buyInDt");
            return (Criteria) this;
        }

        public Criteria andBuyInDtGreaterThanOrEqualTo(String value) {
            addCriterion("buy_in_dt >=", value, "buyInDt");
            return (Criteria) this;
        }

        public Criteria andBuyInDtLessThan(String value) {
            addCriterion("buy_in_dt <", value, "buyInDt");
            return (Criteria) this;
        }

        public Criteria andBuyInDtLessThanOrEqualTo(String value) {
            addCriterion("buy_in_dt <=", value, "buyInDt");
            return (Criteria) this;
        }

        public Criteria andBuyInDtLike(String value) {
            addCriterion("buy_in_dt like", value, "buyInDt");
            return (Criteria) this;
        }

        public Criteria andBuyInDtNotLike(String value) {
            addCriterion("buy_in_dt not like", value, "buyInDt");
            return (Criteria) this;
        }

        public Criteria andBuyInDtIn(List<String> values) {
            addCriterion("buy_in_dt in", values, "buyInDt");
            return (Criteria) this;
        }

        public Criteria andBuyInDtNotIn(List<String> values) {
            addCriterion("buy_in_dt not in", values, "buyInDt");
            return (Criteria) this;
        }

        public Criteria andBuyInDtBetween(String value1, String value2) {
            addCriterion("buy_in_dt between", value1, value2, "buyInDt");
            return (Criteria) this;
        }

        public Criteria andBuyInDtNotBetween(String value1, String value2) {
            addCriterion("buy_in_dt not between", value1, value2, "buyInDt");
            return (Criteria) this;
        }

        public Criteria andBuyInAtIsNull() {
            addCriterion("buy_in_at is null");
            return (Criteria) this;
        }

        public Criteria andBuyInAtIsNotNull() {
            addCriterion("buy_in_at is not null");
            return (Criteria) this;
        }

        public Criteria andBuyInAtEqualTo(Integer value) {
            addCriterion("buy_in_at =", value, "buyInAt");
            return (Criteria) this;
        }

        public Criteria andBuyInAtNotEqualTo(Integer value) {
            addCriterion("buy_in_at <>", value, "buyInAt");
            return (Criteria) this;
        }

        public Criteria andBuyInAtGreaterThan(Integer value) {
            addCriterion("buy_in_at >", value, "buyInAt");
            return (Criteria) this;
        }

        public Criteria andBuyInAtGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_in_at >=", value, "buyInAt");
            return (Criteria) this;
        }

        public Criteria andBuyInAtLessThan(Integer value) {
            addCriterion("buy_in_at <", value, "buyInAt");
            return (Criteria) this;
        }

        public Criteria andBuyInAtLessThanOrEqualTo(Integer value) {
            addCriterion("buy_in_at <=", value, "buyInAt");
            return (Criteria) this;
        }

        public Criteria andBuyInAtIn(List<Integer> values) {
            addCriterion("buy_in_at in", values, "buyInAt");
            return (Criteria) this;
        }

        public Criteria andBuyInAtNotIn(List<Integer> values) {
            addCriterion("buy_in_at not in", values, "buyInAt");
            return (Criteria) this;
        }

        public Criteria andBuyInAtBetween(Integer value1, Integer value2) {
            addCriterion("buy_in_at between", value1, value2, "buyInAt");
            return (Criteria) this;
        }

        public Criteria andBuyInAtNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_in_at not between", value1, value2, "buyInAt");
            return (Criteria) this;
        }

        public Criteria andSellOutDtIsNull() {
            addCriterion("sell_out_dt is null");
            return (Criteria) this;
        }

        public Criteria andSellOutDtIsNotNull() {
            addCriterion("sell_out_dt is not null");
            return (Criteria) this;
        }

        public Criteria andSellOutDtEqualTo(String value) {
            addCriterion("sell_out_dt =", value, "sellOutDt");
            return (Criteria) this;
        }

        public Criteria andSellOutDtNotEqualTo(String value) {
            addCriterion("sell_out_dt <>", value, "sellOutDt");
            return (Criteria) this;
        }

        public Criteria andSellOutDtGreaterThan(String value) {
            addCriterion("sell_out_dt >", value, "sellOutDt");
            return (Criteria) this;
        }

        public Criteria andSellOutDtGreaterThanOrEqualTo(String value) {
            addCriterion("sell_out_dt >=", value, "sellOutDt");
            return (Criteria) this;
        }

        public Criteria andSellOutDtLessThan(String value) {
            addCriterion("sell_out_dt <", value, "sellOutDt");
            return (Criteria) this;
        }

        public Criteria andSellOutDtLessThanOrEqualTo(String value) {
            addCriterion("sell_out_dt <=", value, "sellOutDt");
            return (Criteria) this;
        }

        public Criteria andSellOutDtLike(String value) {
            addCriterion("sell_out_dt like", value, "sellOutDt");
            return (Criteria) this;
        }

        public Criteria andSellOutDtNotLike(String value) {
            addCriterion("sell_out_dt not like", value, "sellOutDt");
            return (Criteria) this;
        }

        public Criteria andSellOutDtIn(List<String> values) {
            addCriterion("sell_out_dt in", values, "sellOutDt");
            return (Criteria) this;
        }

        public Criteria andSellOutDtNotIn(List<String> values) {
            addCriterion("sell_out_dt not in", values, "sellOutDt");
            return (Criteria) this;
        }

        public Criteria andSellOutDtBetween(String value1, String value2) {
            addCriterion("sell_out_dt between", value1, value2, "sellOutDt");
            return (Criteria) this;
        }

        public Criteria andSellOutDtNotBetween(String value1, String value2) {
            addCriterion("sell_out_dt not between", value1, value2, "sellOutDt");
            return (Criteria) this;
        }

        public Criteria andSellOutAtIsNull() {
            addCriterion("sell_out_at is null");
            return (Criteria) this;
        }

        public Criteria andSellOutAtIsNotNull() {
            addCriterion("sell_out_at is not null");
            return (Criteria) this;
        }

        public Criteria andSellOutAtEqualTo(Integer value) {
            addCriterion("sell_out_at =", value, "sellOutAt");
            return (Criteria) this;
        }

        public Criteria andSellOutAtNotEqualTo(Integer value) {
            addCriterion("sell_out_at <>", value, "sellOutAt");
            return (Criteria) this;
        }

        public Criteria andSellOutAtGreaterThan(Integer value) {
            addCriterion("sell_out_at >", value, "sellOutAt");
            return (Criteria) this;
        }

        public Criteria andSellOutAtGreaterThanOrEqualTo(Integer value) {
            addCriterion("sell_out_at >=", value, "sellOutAt");
            return (Criteria) this;
        }

        public Criteria andSellOutAtLessThan(Integer value) {
            addCriterion("sell_out_at <", value, "sellOutAt");
            return (Criteria) this;
        }

        public Criteria andSellOutAtLessThanOrEqualTo(Integer value) {
            addCriterion("sell_out_at <=", value, "sellOutAt");
            return (Criteria) this;
        }

        public Criteria andSellOutAtIn(List<Integer> values) {
            addCriterion("sell_out_at in", values, "sellOutAt");
            return (Criteria) this;
        }

        public Criteria andSellOutAtNotIn(List<Integer> values) {
            addCriterion("sell_out_at not in", values, "sellOutAt");
            return (Criteria) this;
        }

        public Criteria andSellOutAtBetween(Integer value1, Integer value2) {
            addCriterion("sell_out_at between", value1, value2, "sellOutAt");
            return (Criteria) this;
        }

        public Criteria andSellOutAtNotBetween(Integer value1, Integer value2) {
            addCriterion("sell_out_at not between", value1, value2, "sellOutAt");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 12 19:45:26 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}