server:
   port: 9999
spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mylab
      username: root
      password: jin123

management:
   endpoints:
      web:
         exposure:
            include:
               - info
               - health
               - beans
               - caches
               - conditions
               - configprops

myapp:
   log-switch: true