## Freemarker Config ##
spring:
  freemarker:
    suffix: .ftl
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    template-loader-path: classpath:/templates

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:7002/mylab?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: pay_123

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 10088