package com.lijin.mylab.dao.mybatis.mapper;

import com.lijin.mylab.dao.mybatis.model.StockPositionLog;
import com.lijin.mylab.dao.mybatis.model.StockPositionLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockPositionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    long countByExample(StockPositionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    int deleteByExample(StockPositionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    int insert(StockPositionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    int insertSelective(StockPositionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    List<StockPositionLog> selectByExample(StockPositionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    StockPositionLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") StockPositionLog record, @Param("example") StockPositionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    int updateByExample(@Param("record") StockPositionLog record, @Param("example") StockPositionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    int updateByPrimaryKeySelective(StockPositionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stock_position_log
     *
     * @mbg.generated Thu Nov 12 19:45:26 CST 2020
     */
    int updateByPrimaryKey(StockPositionLog record);
}