spring:
   profiles:
      active: dev
   freemarker:
      suffix: .ftl
      allow-request-override: false
      cache: false
      check-template-location: true
      charset: UTF-8
      content-type: text/html
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
      template-loader-path: file:D:\works\github\mylab\src\main\resources\templates
mybatis:
   mapper-locations: classpath:mybatis/mapper/*.xml
